image: docker.ctc.com/ctc/sbt

stages:
  - test
  - publish

unit_test:
  stage: test
  script:
#  - sbt compile
#  - unset JAVA_OPTS http_proxy https_proxy
#  - sbt coverage test
  - sbt test

docker_branch:
  image: docker.ctc.com/ctc/sbt:docker
  stage: publish
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

  - sbt docker:publishLocal

  - docker tag example-akka-cluster/cluster-seeds $CI_REGISTRY_IMAGE:seed-$CI_BUILD_REF_NAME
  - docker tag example-akka-cluster/cluster-listener $CI_REGISTRY_IMAGE:listener-$CI_BUILD_REF_NAME
  - docker tag example-akka-cluster/cluster-agent $CI_REGISTRY_IMAGE:agent-$CI_BUILD_REF_NAME
  - docker tag example-akka-cluster/cluster-multi-agent $CI_REGISTRY_IMAGE:multi-agent-$CI_BUILD_REF_NAME
  - docker tag example-akka-cluster/cluster-client $CI_REGISTRY_IMAGE:client-$CI_BUILD_REF_NAME

  - docker push $CI_REGISTRY_IMAGE:seed-$CI_BUILD_REF_NAME
  - docker push $CI_REGISTRY_IMAGE:listener-$CI_BUILD_REF_NAME
  - docker push $CI_REGISTRY_IMAGE:agent-$CI_BUILD_REF_NAME
  - docker push $CI_REGISTRY_IMAGE:multi-agent-$CI_BUILD_REF_NAME
  - docker push $CI_REGISTRY_IMAGE:client-$CI_BUILD_REF_NAME

  - docker rmi $CI_REGISTRY_IMAGE:seed-$CI_BUILD_REF_NAME
  - docker rmi $CI_REGISTRY_IMAGE:listener-$CI_BUILD_REF_NAME
  - docker rmi $CI_REGISTRY_IMAGE:agent-$CI_BUILD_REF_NAME
  - docker rmi $CI_REGISTRY_IMAGE:multi-agent-$CI_BUILD_REF_NAME
  - docker rmi $CI_REGISTRY_IMAGE:client-$CI_BUILD_REF_NAME
  only:
  - branches
  except:
  - master
  tags:
  - containers

docker_latest:
  image: docker.ctc.com/ctc/sbt:docker
  stage: publish
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

  - sbt docker:publishLocal

  - docker tag example-akka-cluster/cluster-seeds $CI_REGISTRY_IMAGE:seed
  - docker tag example-akka-cluster/cluster-listener $CI_REGISTRY_IMAGE:listener
  - docker tag example-akka-cluster/cluster-agent $CI_REGISTRY_IMAGE:agent
  - docker tag example-akka-cluster/cluster-multi-agent $CI_REGISTRY_IMAGE:multi-agent
  - docker tag example-akka-cluster/cluster-client $CI_REGISTRY_IMAGE:client

  - docker push $CI_REGISTRY_IMAGE:seed
  - docker push $CI_REGISTRY_IMAGE:listener
  - docker push $CI_REGISTRY_IMAGE:agent
  - docker push $CI_REGISTRY_IMAGE:multi-agent
  - docker push $CI_REGISTRY_IMAGE:client

  - docker rmi $CI_REGISTRY_IMAGE:seed
  - docker rmi $CI_REGISTRY_IMAGE:listener
  - docker rmi $CI_REGISTRY_IMAGE:agent
  - docker rmi $CI_REGISTRY_IMAGE:multi-agent
  - docker rmi $CI_REGISTRY_IMAGE:client
  only:
  - master
  tags:
  - containers
