seed-1:
  image: example-akka-cluster/cluster-seeds
  hostname: seed-1
  ports:
    - 2551:2551
  environment:
    CLUSTER_HOST: seed-1
    CLUSTER_SEEDS: seed-1

seed-2:
  image: example-akka-cluster/cluster-seeds
  hostname: seed-2
  ports:
    - 2552:2551
  links:
    - seed-1
  environment:
    CLUSTER_HOST: seed-2
    CLUSTER_SEEDS: seed-1

listener:
  image: example-akka-cluster/cluster-listener
  hostname: listener
  ports:
    - 2550:2551
  links:
    - seed-1
    - seed-2
  environment:
    CLUSTER_SEEDS: seed-1,seed-2
    CLUSTER_HOST: ""
    CLUSTER_PORT: 0

worker-1:
  image: example-akka-cluster/cluster-agent
  hostname: worker-1
  ports:
    - 2553:2551
  links:
    - seed-1
    - seed-2
  environment:
    CLUSTER_SEEDS: seed-1,seed-2
    CLUSTER_HOST: ""
    CLUSTER_PORT: 0

worker-2:
  image: example-akka-cluster/cluster-agent
  hostname: worker-3
  ports:
    - 2554:2551
  links:
    - seed-1
    - seed-2
  environment:
    CLUSTER_SEEDS: seed-1,seed-2
    CLUSTER_HOST: ""
    CLUSTER_PORT: 0

worker-3:
  image: example-akka-cluster/cluster-agent
  hostname: worker-3
  ports:
    - 2555:2551
  links:
    - seed-1
    - seed-2
  environment:
    CLUSTER_SEEDS: seed-1,seed-2
    CLUSTER_HOST: ""
    CLUSTER_PORT: 0

cluster-multi-agent:
  image: example-akka-cluster/cluster-multi-agent
  hostname: cluster-multi-agent
  ports:
    - 2556:2551
  links:
    - seed-1
    - seed-2
  environment:
    CLUSTER_SEEDS: seed-1,seed-2
    CLUSTER_HOST: ""
    CLUSTER_PORT: 0

cluster-client:
  image: example-akka-cluster/cluster-client
  hostname: cluster-client
  ports:
    - 9000:9000
  links:
    - seed-1
    - seed-2
  environment:
    CLUSTER_SEEDS: seed-1,seed-2
    CLUSTER_HOST: ""
    CLUSTER_PORT: 0
