apiVersion: v1
kind: Template
metadata:
  name: akka-cluster-client
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: akka-cluster-client
    name: akka-cluster-client
  spec:
    ports:
    - name: 9000-tcp
      port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      app: akka-cluster-client
      deploymentconfig: akka-cluster-client
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      app: akka-cluster-client
    name: akka-cluster-client
  spec:
    replicas: 1
    selector:
      app: akka-cluster-client
      deploymentconfig: akka-cluster-client
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: akka-cluster-client
          deploymentconfig: akka-cluster-client
      spec:
        containers:
        - name: akka-cluster-client
          image: docker.ctc.com/wassj/example-akka-cluster:client
          env:
          - name: CLUSTER_SEEDS
            value: akka-seed-0.akka-seed,akka-seed-1.akka-seed
          - name: CLUSTER_HOST
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          livenessProbe:
            tcpSocket:
              port: 2551
          ports:
          - containerPort: 2551
            protocol: TCP
          imagePullPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Route
  metadata:
    name: akka-cluster-client
  spec:
    host: example-akka-cluster.openshift.ctc.com
    to:
      kind: Service
      name: akka-cluster-client
      weight: 100
    port:
      targetPort: 9000-tcp
    wildcardPolicy: None
