apiVersion: v1
kind: Template
metadata:
  name: akka-cluster-workers
objects:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      run: akka-modulo-agent
    name: akka-modulo-agent
  spec:
    replicas: 1
    selector:
      matchLabels:
        run: akka-modulo-agent
    template:
      metadata:
        labels:
          run: akka-modulo-agent
      spec:
        containers:
        - name: akka-modulo-agent
          image: docker.ctc.com/wassj/example-akka-cluster:agent
          env:
          - name: CLUSTER_SEEDS
            value: akka-seed-0.akka-seed,akka-seed-1.akka-seed
          - name: CLUSTER_HOST
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          livenessProbe:
            tcpSocket:
              port: 2551
          ports:
          - containerPort: 2551
            protocol: TCP
          imagePullPolicy: Always
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      run: akka-math-agents
    name: akka-math-agents
  spec:
    replicas: 3
    selector:
      matchLabels:
        run: akka-math-agents
    template:
      metadata:
        labels:
          run: akka-math-agents
      spec:
        containers:
        - name: akka-math-agents
          image: docker.ctc.com/wassj/example-akka-cluster:multi-agent
          env:
          - name: CLUSTER_SEEDS
            value: akka-seed-0.akka-seed,akka-seed-1.akka-seed
          - name: CLUSTER_HOST
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          livenessProbe:
            tcpSocket:
              port: 2551
          ports:
          - containerPort: 2551
            protocol: TCP
          imagePullPolicy: Always
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      run: akka-cluster-listener
    name: akka-cluster-listener
  spec:
    replicas: 1
    selector:
      matchLabels:
        run: akka-cluster-listener
    template:
      metadata:
        labels:
          run: akka-cluster-listener
      spec:
        containers:
        - name: akka-cluster-listener
          image: docker.ctc.com/wassj/example-akka-cluster:listener
          env:
          - name: CLUSTER_SEEDS
            value: akka-seed-0.akka-seed,akka-seed-1.akka-seed
          - name: CLUSTER_HOST
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          livenessProbe:
            tcpSocket:
              port: 2551
          ports:
          - containerPort: 2551
            protocol: TCP
          imagePullPolicy: Always
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: akka-cluster-client
    name: akka-cluster-client
  spec:
    ports:
    - name: 9000-tcp
      port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      app: akka-cluster-client
      deployment: akka-cluster-client
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      run: akka-cluster-client
    name: akka-cluster-client
  spec:
    replicas: 1
    selector:
      matchLabels:
        run: akka-cluster-client
    template:
      metadata:
        labels:
          run: akka-cluster-client
      spec:
        containers:
        - name: akka-cluster-client
          image: docker.ctc.com/wassj/example-akka-cluster:client
          env:
          - name: CLUSTER_SEEDS
            value: akka-seed-0.akka-seed,akka-seed-1.akka-seed
          - name: CLUSTER_HOST
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          livenessProbe:
            tcpSocket:
              port: 2551
          ports:
          - containerPort: 2551
            protocol: TCP
          imagePullPolicy: Always

- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      run: akka-math-agent-add
    name: akka-math-agent-add
  spec:
    replicas: 1
    selector:
      matchLabels:
        run: akka-math-agent-add
    template:
      metadata:
        labels:
          run: akka-math-agent-add
      spec:
        containers:
        - name: akka-math-agent-add
          image: docker.ctc.com/wassj/example-akka-cluster:multi-agent
          env:
          - name: CLUSTER_SEEDS
            value: akka-seed-0.akka-seed,akka-seed-1.akka-seed
          - name: CLUSTER_HOST
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: BOOT_ONE_AGENT
            value: add
          livenessProbe:
            tcpSocket:
              port: 2551
          ports:
          - containerPort: 2551
            protocol: TCP
          imagePullPolicy: Always

- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      run: akka-math-agent-sub
    name: akka-math-agent-sub
  spec:
    replicas: 1
    selector:
      matchLabels:
        run: akka-math-agent-sub
    template:
      metadata:
        labels:
          run: akka-math-agent-sub
      spec:
        containers:
        - name: akka-math-agent-sub
          image: docker.ctc.com/wassj/example-akka-cluster:multi-agent
          env:
          - name: CLUSTER_SEEDS
            value: akka-seed-0.akka-seed,akka-seed-1.akka-seed
          - name: CLUSTER_HOST
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: BOOT_ONE_AGENT
            value: sub
          livenessProbe:
            tcpSocket:
              port: 2551
          ports:
          - containerPort: 2551
            protocol: TCP
          imagePullPolicy: Always

- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      run: akka-math-agent-mul
    name: akka-math-agent-mul
  spec:
    replicas: 1
    selector:
      matchLabels:
        run: akka-math-agent-mul
    template:
      metadata:
        labels:
          run: akka-math-agent-mul
      spec:
        containers:
        - name: akka-math-agent-mul
          image: docker.ctc.com/wassj/example-akka-cluster:multi-agent
          env:
          - name: CLUSTER_SEEDS
            value: akka-seed-0.akka-seed,akka-seed-1.akka-seed
          - name: CLUSTER_HOST
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: BOOT_ONE_AGENT
            value: mul
          livenessProbe:
            tcpSocket:
              port: 2551
          ports:
          - containerPort: 2551
            protocol: TCP
          imagePullPolicy: Always

- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      run: akka-math-agent-div
    name: akka-math-agent-div
  spec:
    replicas: 1
    selector:
      matchLabels:
        run: akka-math-agent-div
    template:
      metadata:
        labels:
          run: akka-math-agent-div
      spec:
        containers:
        - name: akka-math-agent-div
          image: docker.ctc.com/wassj/example-akka-cluster:multi-agent
          env:
          - name: CLUSTER_SEEDS
            value: akka-seed-0.akka-seed,akka-seed-1.akka-seed
          - name: CLUSTER_HOST
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: BOOT_ONE_AGENT
            value: div
          livenessProbe:
            tcpSocket:
              port: 2551
          ports:
          - containerPort: 2551
            protocol: TCP
          imagePullPolicy: Always
