apiVersion: v1
kind: Template
metadata:
  name: akka-cluster-workers
objects:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      run: akka-modulo-agent
    name: akka-modulo-agent
  spec:
    replicas: 1
    selector:
      matchLabels:
        run: akka-modulo-agent
    template:
      metadata:
        labels:
          run: akka-modulo-agent
      spec:
        containers:
        - name: akka-modulo-agent
          image: docker.ctc.com/wassj/example-akka-cluster:agent
          env:
          - name: CLUSTER_SEEDS
            value: akka-seed-0.akka-seed,akka-seed-1.akka-seed
          - name: CLUSTER_HOST
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          livenessProbe:
            tcpSocket:
              port: 2551
          ports:
          - containerPort: 2551
            protocol: TCP
          imagePullPolicy: Always
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      run: akka-math-agents
    name: akka-math-agents
  spec:
    replicas: 3
    selector:
      matchLabels:
        run: akka-math-agents
    template:
      metadata:
        labels:
          run: akka-math-agents
      spec:
        containers:
        - name: akka-math-agents
          image: docker.ctc.com/wassj/example-akka-cluster:multi-agent
          env:
          - name: CLUSTER_SEEDS
            value: akka-seed-0.akka-seed,akka-seed-1.akka-seed
          - name: CLUSTER_HOST
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          livenessProbe:
            tcpSocket:
              port: 2551
          ports:
          - containerPort: 2551
            protocol: TCP
          imagePullPolicy: Always
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      run: akka-cluster-listener
    name: akka-cluster-listener
  spec:
    replicas: 1
    selector:
      matchLabels:
        run: akka-cluster-listener
    template:
      metadata:
        labels:
          run: akka-cluster-listener
      spec:
        containers:
        - name: akka-cluster-listener
          image: docker.ctc.com/wassj/example-akka-cluster:listener
          env:
          - name: CLUSTER_SEEDS
            value: akka-seed-0.akka-seed,akka-seed-1.akka-seed
          - name: CLUSTER_HOST
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          livenessProbe:
            tcpSocket:
              port: 2551
          ports:
          - containerPort: 2551
            protocol: TCP
          imagePullPolicy: Always
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      run: akka-cluster-client
    name: akka-cluster-client
  spec:
    replicas: 1
    selector:
      matchLabels:
        run: akka-cluster-client
    template:
      metadata:
        labels:
          run: akka-cluster-client
      spec:
        containers:
        - name: akka-cluster-client
          image: docker.ctc.com/wassj/example-akka-cluster:client
          env:
          - name: CLUSTER_SEEDS
            value: akka-seed-0.akka-seed,akka-seed-1.akka-seed
          - name: CLUSTER_HOST
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          livenessProbe:
            tcpSocket:
              port: 2551
          ports:
          - containerPort: 2551
            protocol: TCP
          imagePullPolicy: Always
